galaxy_info:
  author: Jules Lando
  description: Deploy & run Apache server

  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: CentOS
    versions:
    - all
  - name: RedHat
    versions: 
    - all 

  galaxy_tags:
    - development
    - system
    - docker
    - ubuntu
    - debian
    - centos
    - redhat
    - container
    - dockerized
    - containzerized
