---
- include_tasks: "install_python-library_for_docker.yml"
- name: Copy websites file template
  template:
    src: index.html.j2
    dest: /home/{{system_user}}/index.html
- name: Apache installation
  docker_container:
    name: apache
    image: httpd
    state: started
    ports:
    - "{{ expose_port }}:{{ apache_port }}"
    volumes:
      - /home/{{ system_user }}/index.html:/usr/local/apache2/htdocs/index.html

# debug output
- debug:
    msg:
      - "Setup successfully complete."
      - ""
      - "Apache instance is available on following IP: {{ inventory_hostname }}"
      - "Application expose port: {{ expose_port }}"
