---
# pre_tasks:
- name: Install EPEL repo, git and wget
  yum:
    name:
      - epel-release
      - git
      - wget
    state: present
  when: ansible_distribution == "CentOS"
- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py
- name: install python-pip
  command: python2.7 /tmp/get-pip.py
- name: Install docker python
  pip: name=docker-py

# tasks:
- name: Copy websites file template
  template:
    src: index.html.j2
    dest: /home/admin/index.html
- name: Apache installation
  docker_container:
    name: apache
    image: httpd
    state: started
    ports:
    - "80:80"
    volumes:
      - /home/admin/index.html:/usr/local/apache2/htdocs/index.html

# debug output
- debug:
    msg:
      - "Setup successfully complete."
      - ""
      - "Apache instance is available on following IP: {{ inventory_hostname }}"
